name: C/C++ CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: 1. prepare environment
      run: |
        echo "- check wget, gcc and download libnotes.so";
        pwd
        wget --version
        gcc --version
        wget 'https://domino-1.dmytro.cloud/Files.nsf/all/file/$FILE/libnotes.so' -O libnotes.so -q --show-progress
    - name: 2. build dsapistub1.o
      run: |
        echo "- creating dsapistub1.o";
        gcc src/dsapistub1.c -Inotesapi/include -c -O -w -m64 -DGCC3 -DGCC4 -fno-strict-aliasing -DGCC_LBLB_NOT_SUPPORTED -Wformat -Wall -Wcast-align -Wconversion -DUNIX -DLINUX -DLINUX86 -DND64 -DW32 -DLINUX64 -DW -DLINUX86_64 -DDTRACE -DPTHREAD_KERNEL -D_REENTRANT -DUSE_THREADSAFE_INTERFACES -D_POSIX_THREAD_SAFE_FUNCTIONS -DHANDLE_IS_32BITS -DHAS_IOCP -DHAS_BOOL -DHAS_DLOPEN -DUSE_PTHREAD_INTERFACES -DLARGE64_FILES -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDUNIX64 -DLONGIS64BIT -DPRODUCTION_VERSION -DOVERRIDEDEBUG -fPIC
        ls -la
        echo "- done";
    - name: 3. build libdsapistub1.so
      run: |
        echo "creating so";
        gcc -m64 -DGCC3 -DGCC4 "libnotes.so" -fno-strict-aliasing -DGCC_LBLB_NOT_SUPPORTED -Wformat -Wall -Wcast-align -Wconversion -shared -fPIC -Wl,-Bsymbolic,--whole-archive,-znodefs,-ztext -Wl,--no-whole-archive -Lnotesapi/lib/linux64 -L/lib64 -ldl -lrt -lm -lstdc++ -lpthread -lc -lresolv -lc dsapistub1.o -o libdsapistub1.so
        ls -la
        echo "- done";
    - name: 4. Store artifact in GitHub
      uses: actions/upload-artifact@v4
      with:
        name: libdsapistub1
        path: libdsapistub1.so
        retention-days: 1
        if-no-files-found: error
    - name: 5. Run deploy on Domino server
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://domino-1.dmytro.cloud/DeployGitHub.nsf/start?openagent'
        method: 'POST'
        contentType: application/json
        data: '{"run-id": "${{github.run_id}}", "repo": "${{github.repository}}"}'
        preventFailureOnNoResponse: 'true'
